from vocoder import *
from pitch import *
from osc import *
from audio_in import *
from mixer import *
from filter import *
from amp import *
from eg1 import *
from eg2 import *
from lfo1 import *
from lfo2 import *
